/**
 * User stories for check-in features
 */

import { UserStory, StoryPriority, StoryStatus } from '../types';

export const checkinStories: UserStory[] = [
  {
    id: 'CHECKIN-001',
    epicId: 'EPIC-ENGAGEMENT',
    title: 'Customizable check-in templates',
    asA: 'Administrator',
    iWantTo: 'Configure check-in questions that match our organizational culture',
    soThat: 'I can collect more meaningful engagement data',
    acceptanceCriteria: [
      {
        id: 'AC-C001-1',
        given: 'I am logged in as an administrator',
        when: 'I access the check-in template management screen',
        then: 'Template list and create button are displayed',
        verified: true,
        testIds: ['checkin-templates.spec.ts#access'],
      },
      {
        id: 'AC-C001-2',
        given: 'I have the template creation screen open',
        when: 'I set name, frequency, and custom questions and save',
        then: 'A new template is created and displayed in the list',
        verified: true,
        testIds: ['checkin-templates.spec.ts#create'],
      },
      {
        id: 'AC-C001-3',
        given: 'An organization without templates',
        when: 'I click the create default template button',
        then: 'A standard weekly check-in template is automatically created',
        verified: true,
        testIds: ['checkin-templates.spec.ts#default-creation'],
      },
    ],
    priority: StoryPriority.P0,
    status: StoryStatus.DONE,
    tags: ['checkin', 'template', 'admin'],
    implementedIn: {
      components: [
        '/src/components/checkins/template-manager.tsx',
        '/src/components/checkins/template-form.tsx',
        '/src/components/checkins/create-default-template-button.tsx',
      ],
      apis: [
        '/src/app/api/checkin-templates/route.ts',
        '/src/app/api/checkin-templates/[id]/route.ts',
        '/src/app/api/checkin-templates/ensure-default/route.ts',
      ],
      tests: ['/tests/e2e/checkin-templates.spec.ts'],
    },
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-15'),
    completedAt: new Date('2024-02-15'),
  },
  {
    id: 'CHECKIN-002',
    epicId: 'EPIC-ENGAGEMENT',
    title: 'テンプレートベースのチェックイン作成',
    asA: '従業員',
    iWantTo: '組織が設定したテンプレートでチェックインを行いたい',
    soThat: '一貫性のある振り返りと目標設定ができる',
    acceptanceCriteria: [
      {
        id: 'AC-C002-1',
        given: 'デフォルトテンプレートが設定されている',
        when: 'チェックインページにアクセスする',
        then: 'テンプレート選択とカスタム質問フォームが表示される',
        verified: true,
        testIds: ['checkin-creation.spec.ts#template-form'],
      },
      {
        id: 'AC-C002-2',
        given: 'チェックインフォームを表示している',
        when: 'すべての必須質問に回答して送信する',
        then: 'チェックインが作成され、完了メッセージが表示される',
        verified: true,
        testIds: ['checkin-creation.spec.ts#submit'],
      },
      {
        id: 'AC-C002-3',
        given: '複数のテンプレートが存在する',
        when: '異なるテンプレートを選択する',
        then: '選択したテンプレートの質問が動的に表示される',
        verified: true,
        testIds: ['checkin-creation.spec.ts#template-switch'],
      },
    ],
    priority: StoryPriority.P0,
    status: StoryStatus.DONE,
    tags: ['チェックイン', '従業員', 'カスタマイズ'],
    implementedIn: {
      components: ['/src/components/checkins/template-based-checkin.tsx'],
      apis: ['/src/app/api/checkins/route.ts'],
      tests: ['/tests/e2e/checkin-creation.spec.ts'],
    },
    createdAt: new Date('2024-02-05'),
    updatedAt: new Date('2024-02-15'),
    completedAt: new Date('2024-02-15'),
  },
  {
    id: 'CHECKIN-003',
    epicId: 'EPIC-ENGAGEMENT',
    title: 'チェックイン履歴とインサイト',
    asA: '従業員とマネージャー',
    iWantTo: '過去のチェックイン履歴とトレンドを確認したい',
    soThat: '成長パターンと改善点を把握できる',
    acceptanceCriteria: [
      {
        id: 'AC-C003-1',
        given: 'チェックイン履歴が存在する',
        when: 'チェックイン履歴セクションを確認する',
        then: '過去のチェックイン一覧と基本統計が表示される',
        verified: true,
        testIds: ['checkin-history.spec.ts#display'],
      },
      {
        id: 'AC-C003-2',
        given: '履歴にムード評価データがある',
        when: '統計情報を確認する',
        then: '平均ムードスコアと総チェックイン数が表示される',
        verified: true,
        testIds: ['checkin-history.spec.ts#stats'],
      },
      {
        id: 'AC-C003-3',
        given: '各チェックインエントリを確認している',
        when: '履歴の詳細を表示する',
        then: '使用したテンプレート名、頻度、回答内容が表示される',
        verified: true,
        testIds: ['checkin-history.spec.ts#details'],
      },
    ],
    priority: StoryPriority.P1,
    status: StoryStatus.DONE,
    tags: ['チェックイン', '履歴', '分析'],
    implementedIn: {
      components: ['/src/components/checkins/checkin-history.tsx'],
      apis: ['/src/app/api/checkins/route.ts'],
      tests: ['/tests/e2e/checkin-history.spec.ts'],
    },
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-02-15'),
    completedAt: new Date('2024-02-15'),
  },
  {
    id: 'CHECKIN-004',
    epicId: 'EPIC-ENGAGEMENT',
    title: '頻度カスタマイズとスケジューリング',
    asA: '管理者',
    iWantTo: 'チーム特性に応じてチェックイン頻度を調整したい',
    soThat: '過度な負担なく継続的なエンゲージメントを実現できる',
    acceptanceCriteria: [
      {
        id: 'AC-C004-1',
        given: 'テンプレート編集画面を開いている',
        when: '頻度オプション（毎日、毎週、隔週、毎月、四半期）を選択する',
        then: '選択した頻度がテンプレートに保存される',
        verified: true,
        testIds: ['checkin-frequency.spec.ts#selection'],
      },
      {
        id: 'AC-C004-2',
        given: '異なる頻度のテンプレートが設定されている',
        when: 'チェックイン作成時にテンプレートを選択する',
        then: 'テンプレートの頻度情報が表示される',
        verified: true,
        testIds: ['checkin-frequency.spec.ts#display'],
      },
    ],
    priority: StoryPriority.P1,
    status: StoryStatus.DONE,
    tags: ['チェックイン', '頻度', 'スケジューリング'],
    implementedIn: {
      components: [
        '/src/components/checkins/template-form.tsx',
        '/src/components/checkins/template-based-checkin.tsx',
      ],
      apis: ['/src/app/api/checkin-templates/route.ts'],
      tests: ['/tests/e2e/checkin-frequency.spec.ts'],
    },
    createdAt: new Date('2024-02-12'),
    updatedAt: new Date('2024-02-15'),
    completedAt: new Date('2024-02-15'),
  },
];
